import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { extendTheme } from "@chakra-ui/react";
import Header from "../../component/common/Header/Header";
import Footer from "../../component/common/Footer/Footer";
import "semantic-ui-css/semantic.min.css";
import Recoil from "../../component/Recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Recoil>
          <Header />
          <Providers>{children}</Providers>
          <Footer />
        </Recoil>
      </body>
    </html>
  );
}
